import "./globals.css";

import { Container } from "postcss";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import { ThemePicker } from "./components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sports Events Ticketing App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          inter.className +
          `bg-[#F7F7F8] dark:bg-[#292B32] text-black dark:text-white`
        }
      >
        <ThemePicker />

        {children}
      </body>
    </html>
  );
}
